// global.h
#ifndef _GUI_H_INCLUDE_
#define _GUI_H_INCLUDE_


// GUI
#define NGWINAMP_GUI_SONGRATIO			100
#define NGWINAMP_GUI_VOLUMERATIO		20
#define NGWINAMP_GUI_PANRATIO			10

//#define NGWINAMP_GUI_UPDATEINFOS		0x100
#define NGWINAMP_GUI_UPDATELIST			0x101
#define NGWINAMP_GUILIVE_UPDATESTATUS	0x102
//#define NGWINAMP_GUILIVE_UPDATEINFOS	0x103
#define NGWINAMP_GUILIVE_UPDATELIST		0x104

#define NGWINAMP_GUILIVE_UPDATESTATUS_T	500
//#define NGWINAMP_GUILIVE_UPDATEINFOS_T	10000
#define NGWINAMP_GUILIVE_UPDATELIST_T	30000


#define WM_TASKICON_EVENT				(WM_USER + 1)


#endif //_GUI_H_INCLUDE_
